data:
  embeddings: /home/romain/Documents/BackUp/Special/Projets/Code_IIA/Projet_9/Sceptic/data/articles_embeddings.pickle
  embeddings_jovien: ../data/articles_embeddings.pickle
  metadata: /home/romain/Documents/BackUp/Special/Projets/Code_IIA/Projet_9/Sceptic/data/articles_metadata.csv
  metadata_jovien: ../data/articles_metadata.csv
  clicks: /home/romain/Documents/BackUp/Special/Projets/Code_IIA/Projet_9/Sceptic/data/clicks
  clicks_jovien: ../data/clicks
  clicks_agg: /home/romain/Documents/BackUp/Special/Projets/Code_IIA/Projet_9/Sceptic/data/clicks_agg.csv
  ranking: /home/romain/Documents/BackUp/Special/Projets/Code_IIA/Projet_9/Sceptic/data/books_db.csv

content_filter:
  matrix_size: 10000

collab:
  sample: 5000
  epochs: 1
  ratio_val_test: 0.1
  learning_rate: 0.001
  rand_seed: 42

